// Each new term in the Fibonacci sequence is generated by adding the 
// previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

// create a fibonacci generator that yields individual numbers in the series
// one at a time
function* fibonacci() {
  let former = 0, current = 1, temp;
  while (true) {
    temp = former
    former = current
    current += temp
    yield current
  }
}

const generator = fibonacci()
let val = 0, sum = 0

for (let val = generator.next().value; val < 4000000;) {
  if (val % 2 == 0) {
    sum += val
  }
  val = generator.next().value
}

console.log(sum)